### ISSUE TITLE
LastFM Recommendations not working anymore

### ISSUE THREAD

**Issue by McWizard** [Zetaphor/personal-auto-radio#1]
When running the recommendations script I now encounter the following error:
`An error occurred: Message: element click intercepted: Element <button type="submit" name="submit" class="btn-primary">...</button> is not clickable at point (413, 446). Other element would receive the click: <div class="onetrust-pc-dark-filter ot-fade-in" style="z-index:2147483645;"></div>
  (Session info: chrome=114.0.5735.133)
`

I suppose last.fm changed their website...

**Comment by Zetaphor** [comment]
I just ran it without any issue. Are you using the provided docker container? You can connect to the container at http://localhost:4444 and watch the session live.

What country are you in?

**Comment by McWizard** [comment]
It didn't work multiple times, but when I tried it again now it worked. Maybe it was a short outtage on lastfms side. 
Thanks for the tip to watch the session. If something like that happens again, I'll see if it'll help.

I'm from germany btw.
